version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.3
    - 3.0.3
    - 3.1.1
    - 3.1.2
    - 3.2.1
  - dependency-name: babel-preset-gatsby
    versions:
    - 1.1.0
    - 1.2.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.3
    - 26.5.4
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
  - dependency-name: semantic-release
    versions:
    - 17.4.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: node-notifier
    versions:
    - 8.0.1
